
(function(){'use strict';
const D=window.CITI_DATA,$=id=>document.getElementById(id);
const C={blue:'#0077b8',sky:'#00a6df',red:'#e31937',grid:'rgba(91,124,145,.16)'};
const cfg={displayModeBar:false,responsive:true};
const base={paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{family:'Inter,Segoe UI,Arial',color:'#6f8594',size:9},margin:{l:46,r:15,t:10,b:42},xaxis:{gridcolor:C.grid,zeroline:false,tickfont:{size:8,color:'#718895'}},yaxis:{gridcolor:C.grid,zeroline:false,tickfont:{size:8,color:'#718895'}},legend:{orientation:'h',y:-.18,font:{size:8,color:'#6f8594'}},hoverlabel:{bgcolor:'#173247',font:{color:'#fff',size:10}}};
function plot(id,t,l={}){if(window.Plotly&&$(id))Plotly.react(id,t,{...base,...l},cfg)}
const trill=m=>'$'+(m/1e6).toFixed(2)+'T', bill=b=>'$'+Number(b).toFixed(1)+'B', pct=v=>Number(v).toFixed(2)+'%';
function delta(c,p){if(!p)return'First year in series';const d=(c/p-1)*100;return(d>=0?'▲ ':'▼ ')+Math.abs(d).toFixed(1)+'% vs prior year'}
function renderKPIs(){const y=+$('yearFilter').value,r=D.financialHistory.find(x=>x.year===y),i=D.financialHistory.findIndex(x=>x.year===y),p=i>0?D.financialHistory[i-1]:null;$('currentView').textContent=y+' Financial Overview';$('kpiAssets').textContent=trill(r.assetsM);$('kpiDeposits').textContent=trill(r.depositsM);$('kpiRevenue').textContent=r.revenueB?bill(r.revenueB):'N/A';$('kpiROA').textContent=pct(r.roa);$('kpiROE').textContent=pct(r.roe);$('kpiROTCE').textContent=y===2025?pct(D.operating2025.rotce):'N/A';$('kpiAssetsDelta').textContent=p?delta(r.assetsM,p.assetsM):'First year in series';$('kpiDepositsDelta').textContent=p?delta(r.depositsM,p.depositsM):'First year in series';$('avgLoans').textContent=y===2025?bill(D.operating2025.averageLoansB):'N/A';$('avgDeposits').textContent=y===2025?bill(D.operating2025.averageDepositsB):'N/A';$('loanDepositRatio').textContent=y===2025?(D.operating2025.averageLoansB/D.operating2025.averageDepositsB*100).toFixed(1)+'%':'N/A';$('capitalReturned').textContent=y===2025?bill(D.operating2025.capitalReturnedB):'N/A';$('staffCount').textContent=r.staffK+'K';$('managementCommentary').textContent=y===2025?D.operating2025.commentary:'Select 2025 to view the current management highlight.'}
function renderCharts(){const h=D.financialHistory;
plot('assetsDeposits',[{type:'scatter',mode:'lines+markers',name:'Assets',x:h.map(x=>x.year),y:h.map(x=>x.assetsM/1e6),line:{color:C.blue,width:3},marker:{size:7},hovertemplate:'%{x}<br>Assets $%{y:.2f}T<extra></extra>'},{type:'scatter',mode:'lines+markers',name:'Deposits',x:h.map(x=>x.year),y:h.map(x=>x.depositsM/1e6),line:{color:C.red,width:3},marker:{size:7},hovertemplate:'%{x}<br>Deposits $%{y:.2f}T<extra></extra>'}],{xaxis:{...base.xaxis,dtick:1},yaxis:{...base.yaxis,tickprefix:'$',ticksuffix:'T'}});
plot('returnTrend',[{type:'scatter',mode:'lines+markers',name:'ROA',x:h.map(x=>x.year),y:h.map(x=>x.roa),line:{color:C.sky,width:2.5},marker:{size:6}},{type:'scatter',mode:'lines+markers',name:'ROE',x:h.map(x=>x.year),y:h.map(x=>x.roe),yaxis:'y2',line:{color:C.red,width:2.5},marker:{size:6}}],{xaxis:{...base.xaxis,dtick:1},yaxis:{...base.yaxis,title:'ROA %',ticksuffix:'%'},yaxis2:{overlaying:'y',side:'right',showgrid:false,title:'ROE %',ticksuffix:'%',tickfont:{size:8,color:'#718895'}}});
const a=D.assetComposition2025;plot('assetMix',[{type:'pie',labels:a.map(x=>x.name),values:a.map(x=>x.valueM),hole:.57,marker:{colors:['#073956','#0077b8','#00a6df','#5eb8dd','#e31937','#9fb6c4']},textinfo:'percent',textfont:{size:8}}],{margin:{l:10,r:10,t:8,b:25},legend:{orientation:'h',y:-.18,font:{size:7,color:'#6f8594'}}});
const s=D.segmentGrowth;plot('segmentGrowth',[{type:'bar',orientation:'h',y:s.map(x=>x.name).reverse(),x:s.map(x=>x.value).reverse(),marker:{color:[C.sky,C.blue,C.red]},text:s.map(x=>x.value+'%').reverse(),textposition:'outside'}],{margin:{l:110,r:35,t:10,b:35},xaxis:{...base.xaxis,ticksuffix:'%',range:[0,36]}});
}
function init(){$('yearFilter').innerHTML=D.financialHistory.map(x=>`<option value="${x.year}" ${x.year===2025?'selected':''}>${x.year}</option>`).join('');$('yearFilter').addEventListener('change',renderKPIs);$('fullscreenBtn').addEventListener('click',async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch(e){}});renderKPIs();renderCharts()}
init();})();
